version: '3'

services:
    mongo:
        container_name: mongo
        image: mongo
        volumes:
            - ./data:/data
        ports:
            - '27017:27017'
    backend:
        container_name: backend
        restart: always
        build:
            context: backend
            dockerfile: Dockerfile
        ports:
            - '4000:4000'
        links:
            - mongo
        volumes:
            - ./backend:/app
            - /app/node_modules
    frontend:
        container_name: frontend
        ports:
            - '3000:3000'
        build:
            context: frontend
            dockerfile: Dockerfile
        volumes:
            - ./frontend:/app
            - /app/node_modules
            - /app/.next
